/**
*** @author chrisGrando
*** Classe destinada para a janela gráfica principal do aplicativo.
*** (Contém código gerado automaticamente pela IDE. Recomenda-se não editar
*** esses segmentos com avisos/comentários em inglês)
**/
package app.gui;

import globals.*;
import app.gui.filter.*;
import app.gui.resources.HardCoded;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import sgbd.PostgreSQL;
import sgbd.file.json.JsonBehavior;
import sgbd.file.log.LogBehavior;

public class MainWindow extends javax.swing.JFrame {
    private final PostgreSQL psql;
    private String previousConsoleText = "";

    //Construtor
    public MainWindow() {
        initComponents();
        setWindowTitle();
        setIcon();
        setCustomFonts();
        psql = new PostgreSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser_JSON = new javax.swing.JFileChooser();
        jFileChooser_LOG = new javax.swing.JFileChooser();
        jDialog_Warning = new javax.swing.JDialog();
        jLabel_Message = new javax.swing.JLabel();
        jButton_OK = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        Tab_PSQL = new javax.swing.JPanel();
        jLabel_Host = new javax.swing.JLabel();
        jLabel_Port = new javax.swing.JLabel();
        jLabel_Database = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jTextField_Host = new javax.swing.JTextField();
        jTextField_Port = new javax.swing.JTextField();
        jTextField_Database = new javax.swing.JTextField();
        jTextField_User = new javax.swing.JTextField();
        jPasswordField_DB = new javax.swing.JPasswordField();
        jButton_ConnectDB = new javax.swing.JButton();
        jButton_CreateDB = new javax.swing.JButton();
        Tab_LOG = new javax.swing.JPanel();
        jLabel_TableName = new javax.swing.JLabel();
        jLabel_JsonFile = new javax.swing.JLabel();
        jLabel_LogFile = new javax.swing.JLabel();
        jTextField_TableName = new javax.swing.JTextField();
        jTextField_JsonFile = new javax.swing.JTextField();
        jTextField_LogFile = new javax.swing.JTextField();
        jButton_JsonFile = new javax.swing.JButton();
        jButton_LogFile = new javax.swing.JButton();
        jButton_Simulation = new javax.swing.JButton();
        Tab_QUERY = new javax.swing.JPanel();
        jButton_TemplateCode1 = new javax.swing.JButton();
        jButton_TemplateCode2 = new javax.swing.JButton();
        jButton_TemplateCode3 = new javax.swing.JButton();
        jButton_TemplateCode4 = new javax.swing.JButton();
        jButton_TemplateCode5 = new javax.swing.JButton();
        jButton_TemplateCode6 = new javax.swing.JButton();
        jScrollPane_Query = new javax.swing.JScrollPane();
        jTextArea_Query = new javax.swing.JTextArea();
        jButton_RunQuery = new javax.swing.JButton();
        jScrollPane_Console = new javax.swing.JScrollPane();
        jTextArea_Console = new javax.swing.JTextArea();

        jFileChooser_JSON.setCurrentDirectory(null);
        jFileChooser_JSON.setDialogTitle("Abrir arquivo de metadado (JSON)");
        jFileChooser_JSON.setFileFilter(new JsonFileFilter());
        jFileChooser_JSON.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jFileChooser_LOG.setCurrentDirectory(null);
        jFileChooser_LOG.setDialogTitle("Abrir arquivo de LOG do SGBD");
        jFileChooser_LOG.setFileFilter(new LogFileFilter());
        jFileChooser_LOG.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jDialog_Warning.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_Warning.setTitle("AVISO");
        jDialog_Warning.setMinimumSize(new java.awt.Dimension(420, 140));
        jDialog_Warning.setName("dialogWarning"); // NOI18N
        jDialog_Warning.setResizable(false);
        jDialog_Warning.getContentPane().setLayout(null);

        jLabel_Message.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Message.setText("<INSIRA MENSAGEM DE AVISO AQUI>");
        jDialog_Warning.getContentPane().add(jLabel_Message);
        jLabel_Message.setBounds(5, 0, 410, 70);

        jButton_OK.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_OK.setText("OK");
        jButton_OK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOkWarningButtonClicked(evt);
            }
        });
        jDialog_Warning.getContentPane().add(jButton_OK);
        jButton_OK.setBounds(170, 70, 80, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGBD LOG");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                onWindowOpened(evt);
            }
        });

        jTabbedPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Tab_PSQL.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel_Host.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_Host.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Host.setText("Host");
        jLabel_Host.setToolTipText("");

        jLabel_Port.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_Port.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Port.setText("Port");
        jLabel_Port.setToolTipText("");

        jLabel_Database.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_Database.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Database.setText("Database");
        jLabel_Database.setToolTipText("");

        jLabel_User.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_User.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_User.setText("Usuário");
        jLabel_User.setToolTipText("");

        jLabel_Password.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_Password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Password.setText("Senha");
        jLabel_Password.setToolTipText("");

        jTextField_Host.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jTextField_Port.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jTextField_Database.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jTextField_User.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jPasswordField_DB.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPasswordField_DB.setEchoChar('\u00f8');

        jButton_ConnectDB.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_ConnectDB.setText("Conectar-se ao PostgreSQL");
        jButton_ConnectDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ConnectDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onConnectButtonClicked(evt);
            }
        });

        jButton_CreateDB.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_CreateDB.setText("Criar nova DATABASE e conectar");
        jButton_CreateDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_CreateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreateButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout Tab_PSQLLayout = new javax.swing.GroupLayout(Tab_PSQL);
        Tab_PSQL.setLayout(Tab_PSQLLayout);
        Tab_PSQLLayout.setHorizontalGroup(
            Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_PSQLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_PSQLLayout.createSequentialGroup()
                        .addComponent(jLabel_Password)
                        .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tab_PSQLLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton_ConnectDB, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addComponent(jButton_CreateDB, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addGap(75, 75, 75))
                            .addGroup(Tab_PSQLLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jPasswordField_DB))))
                    .addGroup(Tab_PSQLLayout.createSequentialGroup()
                        .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Database)
                            .addComponent(jLabel_Port)
                            .addComponent(jLabel_User)
                            .addComponent(jLabel_Host))
                        .addGap(18, 18, 18)
                        .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Host)
                            .addComponent(jTextField_User)
                            .addComponent(jTextField_Port)
                            .addComponent(jTextField_Database))))
                .addContainerGap())
        );
        Tab_PSQLLayout.setVerticalGroup(
            Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_PSQLLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Host)
                    .addComponent(jTextField_Host, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Port)
                    .addComponent(jTextField_Port, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Database)
                    .addComponent(jTextField_Database, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_User)
                    .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Password)
                    .addComponent(jPasswordField_DB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Tab_PSQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ConnectDB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CreateDB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPane.addTab("PSQL", Tab_PSQL);

        Tab_LOG.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel_TableName.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_TableName.setText("Nome da tabela");

        jLabel_JsonFile.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_JsonFile.setText("Arquivo JSON");

        jLabel_LogFile.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel_LogFile.setText("Arquivo de LOG");

        jTextField_TableName.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jTextField_JsonFile.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jTextField_LogFile.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jButton_JsonFile.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton_JsonFile.setText("...");
        jButton_JsonFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_JsonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonJsonClicked(evt);
            }
        });

        jButton_LogFile.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton_LogFile.setText("...");
        jButton_LogFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_LogFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonLogClicked(evt);
            }
        });

        jButton_Simulation.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_Simulation.setText("Executar simulação");
        jButton_Simulation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Simulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonSimulationClicked(evt);
            }
        });

        javax.swing.GroupLayout Tab_LOGLayout = new javax.swing.GroupLayout(Tab_LOG);
        Tab_LOG.setLayout(Tab_LOGLayout);
        Tab_LOGLayout.setHorizontalGroup(
            Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_LOGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_LogFile)
                    .addComponent(jLabel_JsonFile)
                    .addComponent(jLabel_TableName))
                .addGap(18, 18, 18)
                .addGroup(Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_TableName)
                    .addComponent(jTextField_JsonFile, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jTextField_LogFile, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_JsonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LogFile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(Tab_LOGLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jButton_Simulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(268, 268, 268))
        );
        Tab_LOGLayout.setVerticalGroup(
            Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_LOGLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TableName)
                    .addComponent(jTextField_TableName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_JsonFile)
                    .addComponent(jTextField_JsonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_JsonFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Tab_LOGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LogFile)
                    .addComponent(jTextField_LogFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LogFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton_Simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jTabbedPane.addTab("LOG", Tab_LOG);

        Tab_QUERY.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jButton_TemplateCode1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_TemplateCode1.setText("SELECT S/ JOIN");
        jButton_TemplateCode1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_TemplateCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTemplateButton1Clicked(evt);
            }
        });

        jButton_TemplateCode2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_TemplateCode2.setText("SELECT C/ JOIN");
        jButton_TemplateCode2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_TemplateCode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTemplateButton2Clicked(evt);
            }
        });

        jButton_TemplateCode3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_TemplateCode3.setText("CREATE TABLE");
        jButton_TemplateCode3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_TemplateCode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTemplateButton3Clicked(evt);
            }
        });

        jButton_TemplateCode4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_TemplateCode4.setText("INSERT INTO TABLE");
        jButton_TemplateCode4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_TemplateCode4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTemplateButton4Clicked(evt);
            }
        });

        jButton_TemplateCode5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_TemplateCode5.setText("UPDATE TABLE");
        jButton_TemplateCode5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_TemplateCode5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTemplateButton5Clicked(evt);
            }
        });

        jButton_TemplateCode6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jButton_TemplateCode6.setText("DELETE FROM TABLE");
        jButton_TemplateCode6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_TemplateCode6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTemplateButton6Clicked(evt);
            }
        });

        jScrollPane_Query.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane_Query.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextArea_Query.setColumns(20);
        jTextArea_Query.setFont(new java.awt.Font("Liberation Mono", 0, 14)); // NOI18N
        jTextArea_Query.setRows(5);
        jTextArea_Query.setText("-- Insira o seu código SQL aqui!\n");
        jTextArea_Query.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane_Query.setViewportView(jTextArea_Query);

        jButton_RunQuery.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton_RunQuery.setText("EXECUTAR");
        jButton_RunQuery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_RunQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRunQueryButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout Tab_QUERYLayout = new javax.swing.GroupLayout(Tab_QUERY);
        Tab_QUERY.setLayout(Tab_QUERYLayout);
        Tab_QUERYLayout.setHorizontalGroup(
            Tab_QUERYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_QUERYLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Query)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab_QUERYLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jButton_RunQuery, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(293, 293, 293))
            .addGroup(Tab_QUERYLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Tab_QUERYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_TemplateCode2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jButton_TemplateCode1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Tab_QUERYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_TemplateCode4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jButton_TemplateCode3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Tab_QUERYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_TemplateCode6, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jButton_TemplateCode5, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        Tab_QUERYLayout.setVerticalGroup(
            Tab_QUERYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_QUERYLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_QUERYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_QUERYLayout.createSequentialGroup()
                        .addComponent(jButton_TemplateCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_TemplateCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab_QUERYLayout.createSequentialGroup()
                        .addComponent(jButton_TemplateCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_TemplateCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tab_QUERYLayout.createSequentialGroup()
                        .addComponent(jButton_TemplateCode5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_TemplateCode6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_Query, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_RunQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane.addTab("QUERY", Tab_QUERY);

        jScrollPane_Console.setBackground(new java.awt.Color(242, 242, 242));
        jScrollPane_Console.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), " CONSOLE ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Monospaced", 2, 12))); // NOI18N

        jTextArea_Console.setEditable(false);
        jTextArea_Console.setColumns(20);
        jTextArea_Console.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea_Console.setRows(5);
        jTextArea_Console.setBorder(null);
        jTextArea_Console.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea_Console.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jScrollPane_Console.setViewportView(jTextArea_Console);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane)
                    .addComponent(jScrollPane_Console))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Console, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Executa ao abrir a janela
    private void onWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowOpened
        String defaultPath;
        
        //Inicializa os campos da aba "PSQL"
        jTextField_Host.setText(PSQL.HOST);
        jTextField_Port.setText(PSQL.PORT);
        jTextField_Database.setText(PSQL.DATABASE);
        jTextField_User.setText(PSQL.USER);
        jPasswordField_DB.setText(PSQL.PASSWORD);
        
        //Inicializa os campos da aba "LOG"
        jTextField_TableName.setText(AppSystem.TABLE_NAME);
        jTextField_JsonFile.setText(AppSystem.JSON_TABLE);
        jTextField_LogFile.setText(AppSystem.SGBD_LOG);
        
        //Diretório padrão para abrir arquivos
        try {
            defaultPath = AppSystem.getJarFolder();
        }
        catch (URISyntaxException error) {
            String msg = "[AVISO] Não foi possível encontrar o diretório padrão...";
            Logger.getGlobal().log(Level.WARNING, msg, error);
            defaultPath = System.getProperty("user.dir");
        }
        
        //Configura o diretório padrão
        jFileChooser_JSON.setCurrentDirectory(new File(defaultPath));
        jFileChooser_LOG.setCurrentDirectory(new File(defaultPath));
        
        //Atualiza console
        this.printEvent(evt.paramString());
        this.updateConsole();
    }//GEN-LAST:event_onWindowOpened

    //Conecta-se ao PostgreSQL em uma database já existente
    private void onConnectButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onConnectButtonClicked
        this.printEvent(evt.paramString());
        
        //Checa se algum campo da aba "PSQL" está em branco
        if(this.isAnyPsqlFieldEmpty()) {
            this.showWarning("Favor preencher todos os campos antes de prosseguir...");
            return;
        }
        
        //Configura os dados do PSQL
        psql.setHostWithPort(jTextField_Host.getText(), jTextField_Port.getText());
        psql.setDatabase(jTextField_Database.getText());
        psql.setUserWithPassword(jTextField_User.getText(), new String(jPasswordField_DB.getPassword()));
        psql.generateURL();
        
        //Realiza a conexão
        psql.connectToPostgres();
        
        //Atualiza console
        this.updateConsole();
    }//GEN-LAST:event_onConnectButtonClicked

    //Cria uma nova database no PostgreSQL e se conecta nela
    private void onCreateButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateButtonClicked
        int response;
        String db = jTextField_Database.getText();
        
        //Checa se algum campo da aba "PSQL" está em branco
        if(this.isAnyPsqlFieldEmpty()) {
            this.showWarning("Favor preencher todos os campos antes de prosseguir...");
            return;
        }
        
        //Pergunta se o usuário tem certeza que deseja continuar
        response = JOptionPane.showOptionDialog(
            this,
            "ATENÇÃO!\nSe já existir uma database com o mesmo nome,\nela será deletada assim como todo seu conteúdo.\n\nTem certeza que deseja continuar?",
            "Continuar?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            null,
            1
        );
        
        //Aborta operação se o usuário NÃO selecionar a opção "sim"
        if(response != JOptionPane.YES_OPTION) {
            this.printEvent(evt.paramString() + ",option=ABORT");
            this.updateConsole();
            return;
        }
        
        //Log de evento
        this.printEvent(evt.paramString() + ",option=PROCEED");
        
        //Configura os dados do PSQL
        psql.setHostWithPort(jTextField_Host.getText(), jTextField_Port.getText());
        psql.setDatabase("postgres"); //Database padrão
        psql.setUserWithPassword(jTextField_User.getText(), new String(jPasswordField_DB.getPassword()));
        psql.generateURL();
        
        //Temporariamente conecta-se na database padrão
        psql.connectToPostgres();
        
        //Cria nova database
        psql.runQuery("drop database if exists " + db + ";");
        psql.runQuery("create database " + db + ";");
        
        //Conecta-se na nova database
        psql.setDatabase(db);
        psql.generateURL();
        psql.connectToPostgres();
        
        //Atualiza console
        this.updateConsole();
    }//GEN-LAST:event_onCreateButtonClicked

    //Botão para selecionar o arquivo de JSON
    private void onButtonJsonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonJsonClicked
        int returnVal = jFileChooser_JSON.showOpenDialog(this);
        
        //Usuário selecionou um arquivo
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //Obtém o caminho de diretório completo do arquivo
            File file = jFileChooser_JSON.getSelectedFile();
            jTextField_JsonFile.setText(file.getAbsolutePath());
        }
        
        //Atualiza console
        this.printEvent(evt.paramString() + ",func=onButtonJsonClicked");
        this.updateConsole();
    }//GEN-LAST:event_onButtonJsonClicked

    //Botão para selecionar o arquivo de LOG do SGBD
    private void onButtonLogClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonLogClicked
        int returnVal = jFileChooser_LOG.showOpenDialog(this);
        
        //Usuário selecionou um arquivo
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //Obtém o caminho de diretório completo do arquivo
            File file = jFileChooser_LOG.getSelectedFile();
            jTextField_LogFile.setText(file.getAbsolutePath());
        }
        
        //Atualiza console
        this.printEvent(evt.paramString() + ",func=onButtonLogClicked");
        this.updateConsole();
    }//GEN-LAST:event_onButtonLogClicked

    //Botão para executar a simulação dos eventos de LOG do SGBD
    private void onButtonSimulationClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onButtonSimulationClicked
        int response;
        final String TABLE = jTextField_TableName.getText();
        final String JSON = jTextField_JsonFile.getText();
        final String LOG = jTextField_LogFile.getText();
        
        //Checa se algum campo da aba "LOG" está em branco
        if(this.isAnyLogFieldEmpty()) {
            this.showWarning("Favor preencher todos os campos antes de prosseguir...");
            return;
        }
        
        //Checa se NÃO está conectado no PostgreSQL
        if(!psql.isConnectedOnPostgres()) {
            this.showWarning("Favor estabelecer conexão no PSQL antes de prosseguir...");
            return;
        }
        
        //Pergunta se o usuário tem certeza que deseja continuar
        response = JOptionPane.showOptionDialog(
            this,
            "ATENÇÃO!\nSe já existir uma tabela com o mesmo nome,\nela será deletada assim como todo seu conteúdo.\n\nTem certeza que deseja continuar?",
            "Continuar?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            null,
            1
        );
        
        //Aborta operação se o usuário NÃO selecionar a opção "sim"
        if(response != JOptionPane.YES_OPTION) {
            this.printEvent(evt.paramString() + ",option=ABORT");
            this.updateConsole();
            return;
        }
        
        //Log de evento
        this.printEvent(evt.paramString() + ",option=PROCEED");
        
        //Obtém dados do arquivo JSON 
        JsonBehavior jb = new JsonBehavior();
        jb.openJsonFile(JSON);
        
        //Exibe conteúdo do arquivo
        System.out.println(jb.showContents());
        
        //Insere dados obtidos no Postgres
        jb.insertDataIntoPostgres(psql, TABLE);
        
        //Exibe o conteúdo da tabela no Postgres
        psql.runQuery("select * from " + TABLE + ";");
        
        //Simula a execução dos comandos do arquivo de log do SGBD
        LogBehavior lb = new LogBehavior();
        lb.openFile(LOG);
        lb.runLogInterpreter(psql, TABLE);
        
        //Exibe a tabela no Postgres após a execução da simulação
        psql.runQuery("select * from " + TABLE + " order by id asc;");
        
        //Atualiza console
        this.updateConsole();
    }//GEN-LAST:event_onButtonSimulationClicked

    //Executa ao fechar a janela
    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        //Desconecta-se do PostgreSQL
        try {
            psql.disconnectFromPostgres();
        }
        catch (SQLException error) {
            String msg = "[FATAL] Não foi possível se desconectar do PostgreSQL...";
            Logger.getGlobal().log(Level.SEVERE, msg, error);
            System.out.println(msg);
        }
        
        //Mensagem do evento
        this.printEvent(evt.paramString());
        System.out.println("########## SOFTWARE ENCERRADO ##########");
    }//GEN-LAST:event_onWindowClosing

    //Botão de template de código SQL para select *sem* join
    private void onTemplateButton1Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTemplateButton1Clicked
        String code;
        
        //Template
        code =  "select *\n";
        code += "from TABLE\n";
        code += "where (CONDITION = true);\n";
        
        //Insere template na área de texto
        jTextArea_Query.append(code);
        
        //Atualiza console
        this.printEvent(evt.paramString());
        this.updateConsole();
    }//GEN-LAST:event_onTemplateButton1Clicked

    //Botão de template de código SQL para select *com* join
    private void onTemplateButton2Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTemplateButton2Clicked
        String code;
        
        //Template
        code =  "select t1.ID, t2.NAME, t2.VALUE\n";
        code += "from TABLE1 t1\n";
        code += "join TABLE2 t2\n";
        code += "on t1.ID = t2.FK_ID\n";
        code += "where (CONDITION = true);\n";
        
        //Insere template na área de texto
        jTextArea_Query.append(code);
        
        //Atualiza console
        this.printEvent(evt.paramString());
        this.updateConsole();
    }//GEN-LAST:event_onTemplateButton2Clicked

    //Botão de template de código SQL para criação de tabela
    private void onTemplateButton3Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTemplateButton3Clicked
        String code;
        
        //Template
        code =  "create table TABLE_NAME(\n";
        code += "    ID serial primary key,\n";
        code += "    NAME varchar(255),\n";
        code += "    VALUE int,\n";
        code += "    DATE_TIME date\n";
        code += ");\n";
        
        //Insere template na área de texto
        jTextArea_Query.append(code);
        
        //Atualiza console
        this.printEvent(evt.paramString());
        this.updateConsole();
    }//GEN-LAST:event_onTemplateButton3Clicked

    //Botão de template de código SQL para inserção de dados na tabela
    private void onTemplateButton4Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTemplateButton4Clicked
        String code;
        
        //Template
        code =  "insert into TABLE(COLUMN1, COLUMN2, COLUMN3)\n";
        code += "values (VALUE1, VALUE2, VALUE3);\n";
        
        //Insere template na área de texto
        jTextArea_Query.append(code);
        
        //Atualiza console
        this.printEvent(evt.paramString());
        this.updateConsole();
    }//GEN-LAST:event_onTemplateButton4Clicked

    //Botão de template de código SQL para atualização de dados na tabela
    private void onTemplateButton5Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTemplateButton5Clicked
        String code;
        
        //Template
        code =  "update TABLE\n";
        code += "set COLUMN1 = VALUE1, COLUMN2 = VALUE2\n";
        code += "where COLUMN_ID = VALUE_FILTER;\n";
        
        //Insere template na área de texto
        jTextArea_Query.append(code);
        
        //Atualiza console
        this.printEvent(evt.paramString());
        this.updateConsole();
    }//GEN-LAST:event_onTemplateButton5Clicked

    //Botão de template de código SQL para remoção de dados na tabela
    private void onTemplateButton6Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTemplateButton6Clicked
        String code;
        
        //Template
        code =  "delete from TABLE\n";
        code += "where COLUMN_ID = VALUE_FILTER;\n";
        
        //Insere template na área de texto
        jTextArea_Query.append(code);
        
        //Atualiza console
        this.printEvent(evt.paramString());
        this.updateConsole();
    }//GEN-LAST:event_onTemplateButton6Clicked

    //Botão para executar código SQL escrito na área de texto
    private void onRunQueryButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRunQueryButtonClicked
        this.printEvent(evt.paramString());
        String sql = jTextArea_Query.getText();
        
        //Checa se NÃO está conectado no PostgreSQL
        if(!psql.isConnectedOnPostgres()) {
            this.showWarning("Favor estabelecer conexão no PSQL antes de prosseguir...");
            return;
        }
        
        //Executa código
        psql.runQuery(sql);
        
        //Atualiza console
        this.updateConsole();
    }//GEN-LAST:event_onRunQueryButtonClicked

    //Fecha janela popup de aviso
    private void onOkWarningButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOkWarningButtonClicked
        jDialog_Warning.dispose();
        
        //Atualiza console
        this.printEvent(evt.paramString() + ",func=onOkWarningButtonClicked");
        this.updateConsole();
    }//GEN-LAST:event_onOkWarningButtonClicked

    //Checa se um dos campos da aba "PSQL" está vazio
    private boolean isAnyPsqlFieldEmpty() {
        final String password = new String(jPasswordField_DB.getPassword());
        
        //Host
        if(jTextField_Host.getText().isBlank())
            return true;
        //Port
        else if(jTextField_Port.getText().isBlank())
            return true;
        //Database
        else if(jTextField_Database.getText().isBlank())
            return true;
        //User
        else if(jTextField_User.getText().isBlank())
            return true;
        //Password
        else if(password.isEmpty())
            return true;
        
        //Todos os campos foram preenchidos
        return false;
    }
    
    //Checa se um dos campos da aba "LOG" está vazio
    private boolean isAnyLogFieldEmpty() {
        //Table
        if(jTextField_TableName.getText().isBlank())
            return true;
        //JSON
        else if(jTextField_JsonFile.getText().isBlank())
            return true;
        //LOG
        else if(jTextField_LogFile.getText().isBlank())
            return true;
        
        //Todos os campos foram preenchidos
        return false;
    }
    
    //Exibe janela de aviso
    private void showWarning(String msg) {
        this.updateConsole();
        jLabel_Message.setText(msg);
        jDialog_Warning.setVisible(true);
        jDialog_Warning.setLocationRelativeTo(null);
    }
    
    //Notificação de evento na janela gráfica
    private void printEvent(String event) {
        System.out.println("*** GUI ***");
        System.out.println(event);
        System.out.println();
    }
    
    //Atualiza o texto do console da janela
    private void updateConsole() {
        String currentConsoleText;
        String consolePath;
        
        //Diretório do arquivo do console
        try {
            consolePath = AppSystem.getJarFolder() + AppSystem.CONSOLE_FILE;
        }
        catch (URISyntaxException error) {
            String msg = "[AVISO] Não foi possível obter o diretório do console...";
            Logger.getGlobal().log(Level.WARNING, msg, error);
            consolePath = System.getProperty("user.dir") + AppSystem.CONSOLE_FILE;
        }
        
        //Lê arquivo do console
        ConsoleReader cr = new ConsoleReader();
        cr.read(consolePath);
        
        //Obtém a(s) última(s) linha(s) adicionada(s) no arquivo do console
        currentConsoleText = cr.getText().replace(this.previousConsoleText, "");
        
        //Exibe o texto no console da janela
        jTextArea_Console.append(currentConsoleText);
        
        //Atualiza variável
        this.previousConsoleText = jTextArea_Console.getText();
    }
    
    //Exibe o ícone do aplicativo
    private void setIcon() {
        HardCoded hc = new HardCoded();
        setIconImage(hc.getIconFile("icon/SGBD_ICON.png"));
    }
    
    //Carrega e aplica as fontes personalizadas na janela
    private void setCustomFonts() {
        final float LABELS = 16f;
        final float TEXTFIELDS = 15f;
        final float TEMPLATES = 14f;
        
        //Obtém as fontes
        HardCoded hc = new HardCoded();
        Font cousine = hc.getTTF("ttf/Cousine.ttf");
        Font gentiumPlus = hc.getTTF("ttf/GentiumPlus.ttf");
        Font aksharUnicode = hc.getTTF("ttf/AksharUnicode.ttf");
        
        //Aborta caso tenha ocorrido algum erro
        if(cousine == null || gentiumPlus == null || aksharUnicode == null)
            return;
        
        //Registra as fontes
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        ge.registerFont(cousine);
        ge.registerFont(gentiumPlus);
        ge.registerFont(aksharUnicode);
        
        //Aplica as fontes nos elementos da janela
        jTabbedPane.setFont(gentiumPlus.deriveFont(14f)); //Abas
        jTextArea_Console.setFont(cousine.deriveFont(14f)); //Console
        jTextArea_Query.setFont(cousine.deriveFont(15f)); //Texto SQL
        jButton_RunQuery.setFont(cousine.deriveFont(Font.BOLD, 18f)); //Executar SQL
        jLabel_Message.setFont(aksharUnicode.deriveFont(15f)); //Mensagem de aviso
        //Rótulos
        jLabel_Host.setFont(aksharUnicode.deriveFont(LABELS));
        jLabel_Port.setFont(aksharUnicode.deriveFont(LABELS));
        jLabel_Database.setFont(aksharUnicode.deriveFont(LABELS));
        jLabel_User.setFont(aksharUnicode.deriveFont(LABELS));
        jLabel_Password.setFont(aksharUnicode.deriveFont(LABELS));
        jLabel_TableName.setFont(aksharUnicode.deriveFont(LABELS));
        jLabel_JsonFile.setFont(aksharUnicode.deriveFont(LABELS));
        jLabel_LogFile.setFont(aksharUnicode.deriveFont(LABELS));
        //Campos de texto
        jTextField_Host.setFont(cousine.deriveFont(TEXTFIELDS));
        jTextField_Port.setFont(cousine.deriveFont(TEXTFIELDS));
        jTextField_Database.setFont(cousine.deriveFont(TEXTFIELDS));
        jTextField_User.setFont(cousine.deriveFont(TEXTFIELDS));
        jPasswordField_DB.setFont(cousine.deriveFont(TEXTFIELDS));
        jTextField_TableName.setFont(cousine.deriveFont(TEXTFIELDS));
        jTextField_JsonFile.setFont(cousine.deriveFont(TEXTFIELDS));
        jTextField_LogFile.setFont(cousine.deriveFont(TEXTFIELDS));
        //Botões genéricos
        jButton_ConnectDB.setFont(cousine.deriveFont(Font.BOLD, 14f));
        jButton_CreateDB.setFont(cousine.deriveFont(Font.BOLD, 14f));
        jButton_Simulation.setFont(cousine.deriveFont(Font.BOLD, 17f));
        jButton_OK.setFont(cousine.deriveFont(Font.BOLD, 16f));
        //Botões de abrir arquivos
        jButton_JsonFile.setFont(cousine.deriveFont(Font.BOLD, 14f));
        jButton_JsonFile.setVerticalAlignment(SwingConstants.TOP);
        jButton_LogFile.setFont(cousine.deriveFont(Font.BOLD, 14f));
        jButton_LogFile.setVerticalAlignment(SwingConstants.TOP);
        //Botões de template de código SQL
        jButton_TemplateCode1.setFont(cousine.deriveFont(TEMPLATES));
        jButton_TemplateCode2.setFont(cousine.deriveFont(TEMPLATES));
        jButton_TemplateCode3.setFont(cousine.deriveFont(TEMPLATES));
        jButton_TemplateCode4.setFont(cousine.deriveFont(TEMPLATES));
        jButton_TemplateCode5.setFont(cousine.deriveFont(TEMPLATES));
        jButton_TemplateCode6.setFont(cousine.deriveFont(TEMPLATES));
    }
    
    //Altera o título da janela
    private void setWindowTitle() {
        String title = AppSystem.getAppName() + " ~ " + AppSystem.getAppVersion();
        setTitle(title);
    }
    
    //Creates new form MainWindow
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tab_LOG;
    private javax.swing.JPanel Tab_PSQL;
    private javax.swing.JPanel Tab_QUERY;
    private javax.swing.JButton jButton_ConnectDB;
    private javax.swing.JButton jButton_CreateDB;
    private javax.swing.JButton jButton_JsonFile;
    private javax.swing.JButton jButton_LogFile;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JButton jButton_RunQuery;
    private javax.swing.JButton jButton_Simulation;
    private javax.swing.JButton jButton_TemplateCode1;
    private javax.swing.JButton jButton_TemplateCode2;
    private javax.swing.JButton jButton_TemplateCode3;
    private javax.swing.JButton jButton_TemplateCode4;
    private javax.swing.JButton jButton_TemplateCode5;
    private javax.swing.JButton jButton_TemplateCode6;
    private javax.swing.JDialog jDialog_Warning;
    private javax.swing.JFileChooser jFileChooser_JSON;
    private javax.swing.JFileChooser jFileChooser_LOG;
    private javax.swing.JLabel jLabel_Database;
    private javax.swing.JLabel jLabel_Host;
    private javax.swing.JLabel jLabel_JsonFile;
    private javax.swing.JLabel jLabel_LogFile;
    private javax.swing.JLabel jLabel_Message;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_Port;
    private javax.swing.JLabel jLabel_TableName;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JPasswordField jPasswordField_DB;
    private javax.swing.JScrollPane jScrollPane_Console;
    private javax.swing.JScrollPane jScrollPane_Query;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextArea_Console;
    private javax.swing.JTextArea jTextArea_Query;
    private javax.swing.JTextField jTextField_Database;
    private javax.swing.JTextField jTextField_Host;
    private javax.swing.JTextField jTextField_JsonFile;
    private javax.swing.JTextField jTextField_LogFile;
    private javax.swing.JTextField jTextField_Port;
    private javax.swing.JTextField jTextField_TableName;
    private javax.swing.JTextField jTextField_User;
    // End of variables declaration//GEN-END:variables
}
